### ISSUE TITLE
Double error messages

### ISSUE THREAD

**Issue by CcMarc** [numinix/ajax_shopping_cart_public#1]
Found the following bug, when you add an item to the cart then login using the default zencart login and already have an item from a previous login then it gives you double error messages:

NOTICE: For your convenience, your current shopping cart has been combined with your shopping cart from your last visit. Please review your shopping cart before checking out.

It displays in on top of the screen inside <div id="messageStackErrors"> which is correct then it displays in         
<div id="messageStackErrorCoupon"> as well which should be displaying coupon related messages only.

**Comment by khe817** [comment]
I was unable to reproduce the bug on our demo site.

The error message WARNING_SHOPPING_CART_COMBINED is added to 2 messageStack sessions: header, and shopping_cart; depends on configuration in admin. In our ajax shopping cart page, I could see it outputs only messageStack session shopping_cart.

The step for checking duplications in cart is done in /includes/modules/pages/login/header_php.php that has nothing to do with our ajax shopping cart module.

**Comment by CcMarc** [comment]
This issue was fixed in last release.
